using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
using System.Data;
using Chess;

namespace Chess.UI
{
	///////////////////////////////////////////////////////////////////////
	/// <summary>
	/// Class.  This class represents a Chess Application's User Interface.
	/// Most of this class is generated by the IDE to simplify GUI editing.
	/// The rest of it acts as a middle-man between the UI-widgets and the
	/// chessApp.
	/// </summary>
	public class ChessForm : Form
	{
		private System.ComponentModel.IContainer components;
		private System.Windows.Forms.Panel board_Panel;
		private System.Windows.Forms.Panel boardStatusBar_Panel;
		private System.Windows.Forms.Button undo_Button;
		private System.Windows.Forms.StatusBar state_StatusBar;
		private System.Windows.Forms.StatusBarPanel turn_StatusBarPanel;
		private System.Windows.Forms.StatusBarPanel gameState_StatusBarPanel;
		private Chess.UI.BoardPanel board_BoardPanel;
		private System.Windows.Forms.StatusBar historyCount_StatusBar;
		private System.Windows.Forms.StatusBarPanel historyCount_StatusBarPanel;
		private System.Windows.Forms.Button redo_Button;
		private System.Windows.Forms.TextBox message_textBox;
		private System.Windows.Forms.Button undoAll_Button;
		private System.Windows.Forms.Button redoAll_Button;
		private System.Windows.Forms.ToolTip undoButton_ToolTip;
		private System.Windows.Forms.ToolTip undoAllButton_ToolTip;
		private System.Windows.Forms.ToolTip redoAllButton_ToolTip;
		private System.Windows.Forms.ToolTip redoButton_ToolTip;
		private System.Windows.Forms.GroupBox white_GroupBox;
		private System.Windows.Forms.RadioButton whiteHuman_RadioButton;
		private System.Windows.Forms.RadioButton whiteAIRandom_RadioButton;
		private System.Windows.Forms.RadioButton whiteAIMinMax_RadioButton;
		private System.Windows.Forms.GroupBox groupBox1;
		private System.Windows.Forms.RadioButton blackAIMinMax_RadioButton;
		private System.Windows.Forms.RadioButton blackAIRandom_RadioButton;
		private System.Windows.Forms.RadioButton blackHuman_RadioButton;
		private System.Windows.Forms.Button play_Button;
		private System.Windows.Forms.Button stop_Button;

		private Player.ControllerTypes whitePlayer;
		private Player.ControllerTypes blackPlayer;
		private System.Windows.Forms.NumericUpDown whiteDepth_NumericUpDown;
		private System.Windows.Forms.NumericUpDown blackDepth_NumericUpDown;
		private System.Windows.Forms.Label whiteDepth_Label;
		private System.Windows.Forms.Label blackDepth_Label;
		private System.Windows.Forms.ProgressBar ai_ProgressBar;

		ChessApp chessApp;

		public ChessForm( ChessApp inChessApp )
		{
			chessApp = inChessApp;

			InitializeComponent();

			this.MouseWheel += new MouseEventHandler( MouseWheelResponder );

			whitePlayer = Player.ControllerTypes.Human;
			blackPlayer = Player.ControllerTypes.Human;

			Bind();
		}

		public void Bind()
		{

			board_BoardPanel.PieceMove += new BoardPanel.MoveEventHandler( chessApp.BoardPanel_PieceMove );
			chessApp.BoardNotice += new BoardNoticeEventHandler( board_BoardPanel.ChessApp_BoardNoticeResponder );
			undo_Button.Click += new EventHandler( chessApp.UndoButton_Click );
			redo_Button.Click += new EventHandler( chessApp.RedoButton_Click );
			undoAll_Button.Click += new EventHandler( chessApp.UndoAllButton_Click );
			redoAll_Button.Click += new EventHandler( chessApp.RedoAllButton_Click );
			play_Button.Click += new EventHandler( chessApp.PlayButton_Click );
			stop_Button.Click += new EventHandler( chessApp.StopButton_Click );

			undoButton_ToolTip.SetToolTip( undo_Button, "Undo One Move" );
			undoAllButton_ToolTip.SetToolTip( undoAll_Button, "Undo All Moves" );
			redoButton_ToolTip.SetToolTip( redo_Button, "Redo One Move" );
			redoAllButton_ToolTip.SetToolTip( redoAll_Button, "Redo All Moves" );
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			this.message_textBox = new System.Windows.Forms.TextBox();
			this.board_Panel = new System.Windows.Forms.Panel();
			this.boardStatusBar_Panel = new System.Windows.Forms.Panel();
			this.state_StatusBar = new System.Windows.Forms.StatusBar();
			this.turn_StatusBarPanel = new System.Windows.Forms.StatusBarPanel();
			this.gameState_StatusBarPanel = new System.Windows.Forms.StatusBarPanel();
			this.undoAll_Button = new System.Windows.Forms.Button();
			this.undo_Button = new System.Windows.Forms.Button();
			this.historyCount_StatusBar = new System.Windows.Forms.StatusBar();
			this.historyCount_StatusBarPanel = new System.Windows.Forms.StatusBarPanel();
			this.redo_Button = new System.Windows.Forms.Button();
			this.redoAll_Button = new System.Windows.Forms.Button();
			this.board_BoardPanel = new Chess.UI.BoardPanel();
			this.undoButton_ToolTip = new System.Windows.Forms.ToolTip(this.components);
			this.redoButton_ToolTip = new System.Windows.Forms.ToolTip(this.components);
			this.undoAllButton_ToolTip = new System.Windows.Forms.ToolTip(this.components);
			this.redoAllButton_ToolTip = new System.Windows.Forms.ToolTip(this.components);
			this.white_GroupBox = new System.Windows.Forms.GroupBox();
			this.whiteDepth_Label = new System.Windows.Forms.Label();
			this.whiteAIMinMax_RadioButton = new System.Windows.Forms.RadioButton();
			this.whiteAIRandom_RadioButton = new System.Windows.Forms.RadioButton();
			this.whiteHuman_RadioButton = new System.Windows.Forms.RadioButton();
			this.whiteDepth_NumericUpDown = new System.Windows.Forms.NumericUpDown();
			this.groupBox1 = new System.Windows.Forms.GroupBox();
			this.blackDepth_Label = new System.Windows.Forms.Label();
			this.blackAIMinMax_RadioButton = new System.Windows.Forms.RadioButton();
			this.blackAIRandom_RadioButton = new System.Windows.Forms.RadioButton();
			this.blackHuman_RadioButton = new System.Windows.Forms.RadioButton();
			this.blackDepth_NumericUpDown = new System.Windows.Forms.NumericUpDown();
			this.play_Button = new System.Windows.Forms.Button();
			this.stop_Button = new System.Windows.Forms.Button();
			this.ai_ProgressBar = new System.Windows.Forms.ProgressBar();
			this.board_Panel.SuspendLayout();
			this.boardStatusBar_Panel.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.turn_StatusBarPanel)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.gameState_StatusBarPanel)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.historyCount_StatusBarPanel)).BeginInit();
			this.white_GroupBox.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.whiteDepth_NumericUpDown)).BeginInit();
			this.groupBox1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.blackDepth_NumericUpDown)).BeginInit();
			this.SuspendLayout();
			// 
			// message_textBox
			// 
			this.message_textBox.Anchor = (((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
				| System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right);
			this.message_textBox.BackColor = System.Drawing.SystemColors.Window;
			this.message_textBox.Enabled = false;
			this.message_textBox.Location = new System.Drawing.Point(432, 16);
			this.message_textBox.Multiline = true;
			this.message_textBox.Name = "message_textBox";
			this.message_textBox.ReadOnly = true;
			this.message_textBox.ScrollBars = System.Windows.Forms.ScrollBars.Both;
			this.message_textBox.Size = new System.Drawing.Size(0, 546);
			this.message_textBox.TabIndex = 1;
			this.message_textBox.TabStop = false;
			this.message_textBox.Text = "";
			this.message_textBox.Visible = false;
			this.message_textBox.WordWrap = false;
			// 
			// board_Panel
			// 
			this.board_Panel.Controls.AddRange(new System.Windows.Forms.Control[] {
																					  this.boardStatusBar_Panel,
																					  this.board_BoardPanel});
			this.board_Panel.Location = new System.Drawing.Point(16, 16);
			this.board_Panel.Name = "board_Panel";
			this.board_Panel.Size = new System.Drawing.Size(400, 424);
			this.board_Panel.TabIndex = 2;
			// 
			// boardStatusBar_Panel
			// 
			this.boardStatusBar_Panel.BackColor = System.Drawing.SystemColors.Control;
			this.boardStatusBar_Panel.Controls.AddRange(new System.Windows.Forms.Control[] {
																							   this.state_StatusBar,
																							   this.undoAll_Button,
																							   this.undo_Button,
																							   this.historyCount_StatusBar,
																							   this.redo_Button,
																							   this.redoAll_Button});
			this.boardStatusBar_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
			this.boardStatusBar_Panel.Location = new System.Drawing.Point(0, 400);
			this.boardStatusBar_Panel.Name = "boardStatusBar_Panel";
			this.boardStatusBar_Panel.Size = new System.Drawing.Size(400, 24);
			this.boardStatusBar_Panel.TabIndex = 0;
			// 
			// state_StatusBar
			// 
			this.state_StatusBar.Dock = System.Windows.Forms.DockStyle.Fill;
			this.state_StatusBar.Name = "state_StatusBar";
			this.state_StatusBar.Panels.AddRange(new System.Windows.Forms.StatusBarPanel[] {
																							   this.turn_StatusBarPanel,
																							   this.gameState_StatusBarPanel});
			this.state_StatusBar.ShowPanels = true;
			this.state_StatusBar.Size = new System.Drawing.Size(280, 24);
			this.state_StatusBar.SizingGrip = false;
			this.state_StatusBar.TabIndex = 0;
			this.state_StatusBar.Text = "statusBar1";
			// 
			// turn_StatusBarPanel
			// 
			this.turn_StatusBarPanel.AutoSize = System.Windows.Forms.StatusBarPanelAutoSize.Spring;
			this.turn_StatusBarPanel.Text = "Turn";
			this.turn_StatusBarPanel.Width = 140;
			// 
			// gameState_StatusBarPanel
			// 
			this.gameState_StatusBarPanel.AutoSize = System.Windows.Forms.StatusBarPanelAutoSize.Spring;
			this.gameState_StatusBarPanel.Text = "State";
			this.gameState_StatusBarPanel.ToolTipText = "State of the game";
			this.gameState_StatusBarPanel.Width = 140;
			// 
			// undoAll_Button
			// 
			this.undoAll_Button.BackColor = System.Drawing.SystemColors.Control;
			this.undoAll_Button.Dock = System.Windows.Forms.DockStyle.Right;
			this.undoAll_Button.Enabled = false;
			this.undoAll_Button.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.undoAll_Button.Location = new System.Drawing.Point(280, 0);
			this.undoAll_Button.Name = "undoAll_Button";
			this.undoAll_Button.Size = new System.Drawing.Size(16, 24);
			this.undoAll_Button.TabIndex = 6;
			this.undoAll_Button.Text = "[";
			// 
			// undo_Button
			// 
			this.undo_Button.BackColor = System.Drawing.SystemColors.Control;
			this.undo_Button.Dock = System.Windows.Forms.DockStyle.Right;
			this.undo_Button.Enabled = false;
			this.undo_Button.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.undo_Button.Location = new System.Drawing.Point(296, 0);
			this.undo_Button.Name = "undo_Button";
			this.undo_Button.Size = new System.Drawing.Size(16, 24);
			this.undo_Button.TabIndex = 3;
			this.undo_Button.Text = "<";
			// 
			// historyCount_StatusBar
			// 
			this.historyCount_StatusBar.Dock = System.Windows.Forms.DockStyle.Right;
			this.historyCount_StatusBar.Location = new System.Drawing.Point(312, 0);
			this.historyCount_StatusBar.Name = "historyCount_StatusBar";
			this.historyCount_StatusBar.Panels.AddRange(new System.Windows.Forms.StatusBarPanel[] {
																									  this.historyCount_StatusBarPanel});
			this.historyCount_StatusBar.ShowPanels = true;
			this.historyCount_StatusBar.Size = new System.Drawing.Size(56, 24);
			this.historyCount_StatusBar.SizingGrip = false;
			this.historyCount_StatusBar.TabIndex = 4;
			this.historyCount_StatusBar.Text = "statusBar2";
			// 
			// historyCount_StatusBarPanel
			// 
			this.historyCount_StatusBarPanel.Alignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.historyCount_StatusBarPanel.AutoSize = System.Windows.Forms.StatusBarPanelAutoSize.Contents;
			this.historyCount_StatusBarPanel.BorderStyle = System.Windows.Forms.StatusBarPanelBorderStyle.Raised;
			this.historyCount_StatusBarPanel.Text = "000/000";
			this.historyCount_StatusBarPanel.ToolTipText = "# of Moves in Game / Total # of Moves in the History";
			this.historyCount_StatusBarPanel.Width = 55;
			// 
			// redo_Button
			// 
			this.redo_Button.BackColor = System.Drawing.SystemColors.Control;
			this.redo_Button.Dock = System.Windows.Forms.DockStyle.Right;
			this.redo_Button.Enabled = false;
			this.redo_Button.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.redo_Button.Location = new System.Drawing.Point(368, 0);
			this.redo_Button.Name = "redo_Button";
			this.redo_Button.Size = new System.Drawing.Size(16, 24);
			this.redo_Button.TabIndex = 5;
			this.redo_Button.Text = ">";
			// 
			// redoAll_Button
			// 
			this.redoAll_Button.BackColor = System.Drawing.SystemColors.Control;
			this.redoAll_Button.Dock = System.Windows.Forms.DockStyle.Right;
			this.redoAll_Button.Enabled = false;
			this.redoAll_Button.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.redoAll_Button.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.redoAll_Button.Location = new System.Drawing.Point(384, 0);
			this.redoAll_Button.Name = "redoAll_Button";
			this.redoAll_Button.Size = new System.Drawing.Size(16, 24);
			this.redoAll_Button.TabIndex = 7;
			this.redoAll_Button.Text = "]";
			// 
			// board_BoardPanel
			// 
			this.board_BoardPanel.Dock = System.Windows.Forms.DockStyle.Top;
			// TODO: Code generation for 'this.board_BoardPanel.MoversBitBoard' failed because of Exception 'Invalid Primitive Type: System.UInt64. Only CLS compliant primitive types can be used. Consider using CodeObjectCreateExpression.'.
			// TODO: Code generation for 'this.board_BoardPanel.MovesBitBoard' failed because of Exception 'Invalid Primitive Type: System.UInt64. Only CLS compliant primitive types can be used. Consider using CodeObjectCreateExpression.'.
			this.board_BoardPanel.Name = "board_BoardPanel";
			this.board_BoardPanel.Size = new System.Drawing.Size(400, 400);
			this.board_BoardPanel.TabIndex = 1;
			// 
			// white_GroupBox
			// 
			this.white_GroupBox.Controls.AddRange(new System.Windows.Forms.Control[] {
																						 this.whiteDepth_Label,
																						 this.whiteAIMinMax_RadioButton,
																						 this.whiteAIRandom_RadioButton,
																						 this.whiteHuman_RadioButton,
																						 this.whiteDepth_NumericUpDown});
			this.white_GroupBox.Location = new System.Drawing.Point(16, 448);
			this.white_GroupBox.Name = "white_GroupBox";
			this.white_GroupBox.Size = new System.Drawing.Size(136, 120);
			this.white_GroupBox.TabIndex = 3;
			this.white_GroupBox.TabStop = false;
			this.white_GroupBox.Text = "White";
			// 
			// whiteDepth_Label
			// 
			this.whiteDepth_Label.Location = new System.Drawing.Point(8, 88);
			this.whiteDepth_Label.Name = "whiteDepth_Label";
			this.whiteDepth_Label.Size = new System.Drawing.Size(40, 23);
			this.whiteDepth_Label.TabIndex = 4;
			this.whiteDepth_Label.Text = "Depth:";
			this.whiteDepth_Label.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// whiteAIMinMax_RadioButton
			// 
			this.whiteAIMinMax_RadioButton.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right);
			this.whiteAIMinMax_RadioButton.Location = new System.Drawing.Point(8, 64);
			this.whiteAIMinMax_RadioButton.Name = "whiteAIMinMax_RadioButton";
			this.whiteAIMinMax_RadioButton.Size = new System.Drawing.Size(120, 24);
			this.whiteAIMinMax_RadioButton.TabIndex = 2;
			this.whiteAIMinMax_RadioButton.Text = "AI (MinMax)";
			this.whiteAIMinMax_RadioButton.Click += new System.EventHandler(this.WhiteRadioButtons_Click);
			// 
			// whiteAIRandom_RadioButton
			// 
			this.whiteAIRandom_RadioButton.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right);
			this.whiteAIRandom_RadioButton.Location = new System.Drawing.Point(8, 40);
			this.whiteAIRandom_RadioButton.Name = "whiteAIRandom_RadioButton";
			this.whiteAIRandom_RadioButton.Size = new System.Drawing.Size(120, 24);
			this.whiteAIRandom_RadioButton.TabIndex = 1;
			this.whiteAIRandom_RadioButton.Text = "AI (Random)";
			this.whiteAIRandom_RadioButton.Click += new System.EventHandler(this.WhiteRadioButtons_Click);
			// 
			// whiteHuman_RadioButton
			// 
			this.whiteHuman_RadioButton.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right);
			this.whiteHuman_RadioButton.Checked = true;
			this.whiteHuman_RadioButton.Location = new System.Drawing.Point(8, 16);
			this.whiteHuman_RadioButton.Name = "whiteHuman_RadioButton";
			this.whiteHuman_RadioButton.Size = new System.Drawing.Size(120, 24);
			this.whiteHuman_RadioButton.TabIndex = 0;
			this.whiteHuman_RadioButton.TabStop = true;
			this.whiteHuman_RadioButton.Text = "Human";
			this.whiteHuman_RadioButton.Click += new System.EventHandler(this.WhiteRadioButtons_Click);
			// 
			// whiteDepth_NumericUpDown
			// 
			this.whiteDepth_NumericUpDown.Location = new System.Drawing.Point(48, 88);
			this.whiteDepth_NumericUpDown.Maximum = new System.Decimal(new int[] {
																					 6,
																					 0,
																					 0,
																					 0});
			this.whiteDepth_NumericUpDown.Minimum = new System.Decimal(new int[] {
																					 1,
																					 0,
																					 0,
																					 0});
			this.whiteDepth_NumericUpDown.Name = "whiteDepth_NumericUpDown";
			this.whiteDepth_NumericUpDown.Size = new System.Drawing.Size(40, 20);
			this.whiteDepth_NumericUpDown.TabIndex = 3;
			this.whiteDepth_NumericUpDown.Value = new System.Decimal(new int[] {
																				   3,
																				   0,
																				   0,
																				   0});
			this.whiteDepth_NumericUpDown.ValueChanged += new System.EventHandler(this.whiteDepth_NumericUpDown_ValueChanged);
			// 
			// groupBox1
			// 
			this.groupBox1.Controls.AddRange(new System.Windows.Forms.Control[] {
																					this.blackDepth_Label,
																					this.blackAIMinMax_RadioButton,
																					this.blackAIRandom_RadioButton,
																					this.blackHuman_RadioButton,
																					this.blackDepth_NumericUpDown});
			this.groupBox1.Location = new System.Drawing.Point(168, 448);
			this.groupBox1.Name = "groupBox1";
			this.groupBox1.Size = new System.Drawing.Size(136, 120);
			this.groupBox1.TabIndex = 4;
			this.groupBox1.TabStop = false;
			this.groupBox1.Text = "Black";
			// 
			// blackDepth_Label
			// 
			this.blackDepth_Label.Location = new System.Drawing.Point(8, 88);
			this.blackDepth_Label.Name = "blackDepth_Label";
			this.blackDepth_Label.Size = new System.Drawing.Size(40, 23);
			this.blackDepth_Label.TabIndex = 5;
			this.blackDepth_Label.Text = "Depth:";
			this.blackDepth_Label.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// blackAIMinMax_RadioButton
			// 
			this.blackAIMinMax_RadioButton.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right);
			this.blackAIMinMax_RadioButton.Location = new System.Drawing.Point(8, 64);
			this.blackAIMinMax_RadioButton.Name = "blackAIMinMax_RadioButton";
			this.blackAIMinMax_RadioButton.Size = new System.Drawing.Size(120, 24);
			this.blackAIMinMax_RadioButton.TabIndex = 2;
			this.blackAIMinMax_RadioButton.Text = "AI (MinMax)";
			this.blackAIMinMax_RadioButton.Click += new System.EventHandler(this.BlackRadioButtons_Click);
			// 
			// blackAIRandom_RadioButton
			// 
			this.blackAIRandom_RadioButton.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right);
			this.blackAIRandom_RadioButton.Location = new System.Drawing.Point(8, 40);
			this.blackAIRandom_RadioButton.Name = "blackAIRandom_RadioButton";
			this.blackAIRandom_RadioButton.Size = new System.Drawing.Size(120, 24);
			this.blackAIRandom_RadioButton.TabIndex = 1;
			this.blackAIRandom_RadioButton.Text = "AI (Random)";
			this.blackAIRandom_RadioButton.Click += new System.EventHandler(this.BlackRadioButtons_Click);
			// 
			// blackHuman_RadioButton
			// 
			this.blackHuman_RadioButton.Anchor = ((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
				| System.Windows.Forms.AnchorStyles.Right);
			this.blackHuman_RadioButton.Checked = true;
			this.blackHuman_RadioButton.Location = new System.Drawing.Point(8, 16);
			this.blackHuman_RadioButton.Name = "blackHuman_RadioButton";
			this.blackHuman_RadioButton.Size = new System.Drawing.Size(120, 24);
			this.blackHuman_RadioButton.TabIndex = 0;
			this.blackHuman_RadioButton.TabStop = true;
			this.blackHuman_RadioButton.Text = "Human";
			this.blackHuman_RadioButton.Click += new System.EventHandler(this.BlackRadioButtons_Click);
			// 
			// blackDepth_NumericUpDown
			// 
			this.blackDepth_NumericUpDown.Location = new System.Drawing.Point(48, 88);
			this.blackDepth_NumericUpDown.Maximum = new System.Decimal(new int[] {
																					 6,
																					 0,
																					 0,
																					 0});
			this.blackDepth_NumericUpDown.Minimum = new System.Decimal(new int[] {
																					 1,
																					 0,
																					 0,
																					 0});
			this.blackDepth_NumericUpDown.Name = "blackDepth_NumericUpDown";
			this.blackDepth_NumericUpDown.Size = new System.Drawing.Size(40, 20);
			this.blackDepth_NumericUpDown.TabIndex = 4;
			this.blackDepth_NumericUpDown.Value = new System.Decimal(new int[] {
																				   3,
																				   0,
																				   0,
																				   0});
			this.blackDepth_NumericUpDown.ValueChanged += new System.EventHandler(this.blackDepth_NumericUpDown_ValueChanged);
			// 
			// play_Button
			// 
			this.play_Button.BackColor = System.Drawing.SystemColors.Control;
			this.play_Button.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.play_Button.Location = new System.Drawing.Point(320, 488);
			this.play_Button.Name = "play_Button";
			this.play_Button.Size = new System.Drawing.Size(96, 32);
			this.play_Button.TabIndex = 7;
			this.play_Button.Text = "Start AI";
			// 
			// stop_Button
			// 
			this.stop_Button.BackColor = System.Drawing.SystemColors.Control;
			this.stop_Button.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.stop_Button.Location = new System.Drawing.Point(320, 528);
			this.stop_Button.Name = "stop_Button";
			this.stop_Button.Size = new System.Drawing.Size(96, 32);
			this.stop_Button.TabIndex = 8;
			this.stop_Button.Text = "Stop AI";
			// 
			// ai_ProgressBar
			// 
			this.ai_ProgressBar.Location = new System.Drawing.Point(320, 456);
			this.ai_ProgressBar.Name = "ai_ProgressBar";
			this.ai_ProgressBar.Size = new System.Drawing.Size(96, 16);
			this.ai_ProgressBar.TabIndex = 9;
			// 
			// ChessForm
			// 
			this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
			this.ClientSize = new System.Drawing.Size(426, 576);
			this.Controls.AddRange(new System.Windows.Forms.Control[] {
																		  this.ai_ProgressBar,
																		  this.stop_Button,
																		  this.play_Button,
																		  this.white_GroupBox,
																		  this.board_Panel,
																		  this.message_textBox,
																		  this.groupBox1});
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.MaximizeBox = false;
			this.Name = "ChessForm";
			this.Text = "Chess";
			this.board_Panel.ResumeLayout(false);
			this.boardStatusBar_Panel.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.turn_StatusBarPanel)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.gameState_StatusBarPanel)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.historyCount_StatusBarPanel)).EndInit();
			this.white_GroupBox.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.whiteDepth_NumericUpDown)).EndInit();
			this.groupBox1.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.blackDepth_NumericUpDown)).EndInit();
			this.ResumeLayout(false);

		}
		#endregion

		public void AI_ProgressAnnouncementResponder( object o, ProgressEventArgs e )
		{
			ai_ProgressBar.Value = e.percent;
		}

		public void LockBoard( object o, EventArgs e )
		{
			board_BoardPanel.LockBoard();
		}
		public void UnLockBoard( object o, EventArgs e )
		{
			board_BoardPanel.UnLockBoard();
		}

		private void WhiteRadioButtons_Click(object sender, System.EventArgs e)
		{
			Player.ControllerTypes oldWhiteController = whitePlayer;
			RadioButton rb = (RadioButton) sender;

			if ( rb == whiteHuman_RadioButton && whitePlayer != Player.ControllerTypes.Human )
				whitePlayer = Player.ControllerTypes.Human;
			else if ( rb == whiteAIRandom_RadioButton && whitePlayer != Player.ControllerTypes.AI_Random )
				whitePlayer = Player.ControllerTypes.AI_Random;
			else if ( rb == whiteAIMinMax_RadioButton && whitePlayer != Player.ControllerTypes.AI_MinMax )
				whitePlayer = Player.ControllerTypes.AI_MinMax;

			if ( oldWhiteController != whitePlayer )
				chessApp.PlayerChange( Player.WHITE, whitePlayer );
		}

		private void BlackRadioButtons_Click(object sender, System.EventArgs e)
		{
			Player.ControllerTypes oldBlackController = blackPlayer;
			RadioButton rb = (RadioButton) sender;

			if ( rb == blackHuman_RadioButton && blackPlayer != Player.ControllerTypes.Human )
				blackPlayer = Player.ControllerTypes.Human;
			else if ( rb == blackAIRandom_RadioButton && blackPlayer != Player.ControllerTypes.AI_Random )
				blackPlayer = Player.ControllerTypes.AI_Random;
			else if ( rb == blackAIMinMax_RadioButton && blackPlayer != Player.ControllerTypes.AI_MinMax )
				blackPlayer = Player.ControllerTypes.AI_MinMax;

			if ( oldBlackController != blackPlayer )
				chessApp.PlayerChange( Player.BLACK, blackPlayer );
		}

		public int GetDepth( int color )
		{
			if ( color == Player.WHITE )
				return (int) whiteDepth_NumericUpDown.Value;
			else
				return (int) blackDepth_NumericUpDown.Value;
		}

		private void whiteDepth_NumericUpDown_ValueChanged(object sender, System.EventArgs e)
		{
			if ( whitePlayer == Player.ControllerTypes.AI_MinMax )
				chessApp.PlayerChange( Player.WHITE, whitePlayer );
			else
				chessApp.StopGame();

		}

		private void blackDepth_NumericUpDown_ValueChanged(object sender, System.EventArgs e)
		{
			if ( blackPlayer == Player.ControllerTypes.AI_MinMax )
				chessApp.PlayerChange( Player.BLACK, blackPlayer );	
			else
				chessApp.StopGame();
		}

		private void MouseWheelResponder(object sender, System.Windows.Forms.MouseEventArgs e)
		{
			if ( board_Panel.Bounds.Contains(e.X, e.Y) )
				chessApp.UndoRedoSeveral( e.Delta / 120 );
		}

		public string TurnText
		{
			get
			{
				return turn_StatusBarPanel.Text;
			}
			set
			{
				turn_StatusBarPanel.Text = value;
			}
		}
		public string StateText
		{
			get
			{
				return gameState_StatusBarPanel.Text;
			}
			set
			{
				gameState_StatusBarPanel.Text = value;
			}
		}

		public string UndoRedoMessageText
		{
			get
			{
				return historyCount_StatusBarPanel.Text;
			}
			set
			{
				historyCount_StatusBarPanel.Text = value;
				historyCount_StatusBar.Width = historyCount_StatusBarPanel.Width;
			}
		}
		public bool EnableUndo
		{
			get
			{
				return undo_Button.Enabled;
			}
			set
			{
				undo_Button.Enabled = value;
				undoAll_Button.Enabled = value;
			}
		}
		public bool EnableRedo
		{
			get
			{
				return redo_Button.Enabled;
			}
			set
			{
				redo_Button.Enabled = value;
				redoAll_Button.Enabled = value;
			}
		}
		public string MessageAppend
		{
			set
			{
				string previousMessage = MessageText;
				if ( previousMessage.Length == 0 )
					message_textBox.Text = value;
				else
					message_textBox.Text += Environment.NewLine + value;
			}
		}
		public string MessageText
		{
			get
			{
				return message_textBox.Text;
			}
			set
			{
				message_textBox.Text = value;
			}
		}
	}
}
